<a href="https://colab.research.google.com/github/guslmo1444-maker/Aurora-Siger/blob/main/ML2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

uri = "https://gist.githubusercontent.com/guilhermesilveira/b9dd8e4b62b9e22ebcb9c8e89c271de4/raw/c69ec4b708fba03c445397b6a361db4345c83d7a/tracking.csv"

In [ ]:
dados = pd.read_csv(uri)
dados.head()

   inicial  palestras  contato  comprou  patrocinio
0        1          1        0        0           0
1        1          1        0        0           0
2        1          1        0        0           0
3        1          1        0        0           0
4        1          1        0        0           0

In [ ]:
y = dados ["comprou"]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: comprou, dtype: int64

In [ ]:
x = dados [["inicial", 	"palestras", 	"contato", 	"patrocinio"]]
x.head()

   inicial  palestras  contato  patrocinio
0        1          1        0           0
1        1          1        0           0
2        1          1        0           0
3        1          1        0           0
4        1          1        0           0

In [ ]:
dados.shape

(99, 5)

In [ ]:
treino_x = x[:75]
treino_y = y[:75]

teste_x = x [75:]
teste_y = y [75:]

print (f'Treinaremos com {len(treino_x)} elementos')
print (f'Testando com {len(teste_x)} elementos')

Treinaremos com 75 elementos
Testando com 24 elementos

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score (teste_y, previsoes) * 100
print (f"A acurácia foi de {acuracia:.2f}%")

A acurácia foi de 95.83%

#Usando a biblioteca para separar treino e teste

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

SEED = 4364
treino_x, teste_x, treino_y, teste_y  =  train_test_split(x, y, random_state= SEED, stratify=y)

print (f'Treinaremos com {len(treino_x)} elementos')
print (f'Testando com {len(teste_x)} elementos')


modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score (teste_y, previsoes) * 100
print (f"A acurácia foi de {acuracia:.2f}%")

Treinaremos com 74 elementos
Testando com 25 elementos
A acurácia foi de 100.00%

In [ ]:
treino_y.value_counts()

comprou
0    49
1    25
Name: count, dtype: int64

In [ ]:
teste_y.value_counts()

comprou
0    17
1     8
Name: count, dtype: int64